# Generated by Django 4.1.7 on 2023-03-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_voice',
            field=models.FileField(blank=True, null=True, upload_to='voices/'),
        ),
    ]
